import { useEffect, useMemo, useState, type ReactNode } from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ErrorBoundary } from "@/components/error-boundary";
import { Toaster } from "@/components/ui/toaster";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Link, Route, Switch, Router as WouterRouter, useLocation, useParams } from "wouter";
import { ArrowLeft, ArrowRight, BadgePercent, Calculator, CalendarClock, CalendarDays, ChevronRight, CircleDollarSign, Clock3, Copy, Dumbbell, FileText, Fuel, Gauge, HeartPulse, Home as HomeIcon, Info, Landmark, Menu, Moon, Percent, PiggyBank, ReceiptText, RotateCcw, Ruler, Search, Scale, ShieldCheck, Sparkles, Split, Star, Sun, Table2, Timer, TrendingUp, Utensils, Wallet, WalletCards, X, Zap } from "lucide-react";
import NotFound from "@/pages/not-found";

const queryClient = new QueryClient();
type Calc = { slug: string; title: string; description: string; category: string; icon: typeof Calculator };

const CALCS: Calc[] = [
  { slug: "basic-calculator", title: "Basic Calculator", description: "A fast, keyboard-friendly everyday calculator.", category: "Everyday", icon: Calculator },
  { slug: "percentage-calculator", title: "Percentage", description: "Find percentages, changes, and proportions.", category: "Math", icon: Percent },
  { slug: "emi-calculator", title: "EMI Calculator", description: "Plan monthly loan payments with clarity.", category: "Money", icon: CircleDollarSign },
  { slug: "sip-calculator", title: "SIP Calculator", description: "See how monthly investing can compound.", category: "Money", icon: TrendingUp },
  { slug: "gst-calculator", title: "GST Calculator", description: "Add or remove tax from any price.", category: "Money", icon: WalletCards },
  { slug: "discount-calculator", title: "Discount", description: "Know the real price after a discount.", category: "Shopping", icon: PiggyBank },
  { slug: "age-calculator", title: "Age Calculator", description: "Years, months, days, and your next birthday.", category: "Date & Time", icon: CalendarDays },
  { slug: "bmi-calculator", title: "BMI Calculator", description: "A quick weight-to-height health check.", category: "Health", icon: Scale },
  { slug: "bmr-calculator", title: "BMR Calculator", description: "Estimate your daily energy needs.", category: "Health", icon: HeartPulse },
  { slug: "simple-interest-calculator", title: "Simple Interest", description: "Calculate interest without the guesswork.", category: "Money", icon: CircleDollarSign },
  { slug: "compound-interest-calculator", title: "Compound Interest", description: "Model growth across compounding schedules.", category: "Money", icon: TrendingUp },
  { slug: "tip-calculator", title: "Tip Calculator", description: "Split a bill and tip in a few taps.", category: "Everyday", icon: WalletCards },
  { slug: "salary-calculator", title: "Salary Estimate", description: "Turn annual pay into a useful monthly view.", category: "Money", icon: WalletCards },
  { slug: "date-difference-calculator", title: "Date Difference", description: "Count the exact time between two dates.", category: "Date & Time", icon: Clock3 },
  { slug: "unit-converter", title: "Universal Unit Converter", description: "Convert common units without leaving the page.", category: "Conversion", icon: Table2 },
  { slug: "currency-calculator", title: "Currency Calculator", description: "Convert with your own editable offline rates.", category: "Conversion", icon: CircleDollarSign },
  { slug: "fraction-calculator", title: "Fraction Calculator", description: "Add, subtract, multiply, or divide fractions.", category: "Math", icon: Split },
  { slug: "average-calculator", title: "Average Calculator", description: "Find the mean, total, and count instantly.", category: "Math", icon: TrendingUp },
  { slug: "ratio-calculator", title: "Ratio Calculator", description: "Scale recipes, mixes, and everyday ratios.", category: "Math", icon: Ruler },
  { slug: "scientific-calculator", title: "Scientific Calculator", description: "Powers, roots, logs, and trigonometry.", category: "Math", icon: Calculator },
  { slug: "loan-calculator", title: "Loan Calculator", description: "See payments, interest, and payoff totals.", category: "Money", icon: Landmark },
  { slug: "savings-calculator", title: "Savings Goal", description: "Turn a goal into a monthly saving plan.", category: "Money", icon: Wallet },
  { slug: "tax-calculator", title: "Tax Calculator", description: "Estimate tax and your after-tax amount.", category: "Money", icon: ReceiptText },
  { slug: "calorie-calculator", title: "Calorie Calculator", description: "Estimate daily calories from your routine.", category: "Health", icon: Utensils },
  { slug: "ideal-weight-calculator", title: "Ideal Weight", description: "Explore a general healthy weight range.", category: "Health", icon: Gauge },
  { slug: "days-between-calculator", title: "Days Between Dates", description: "Count the days between two dates.", category: "Date & Time", icon: CalendarClock },
  { slug: "time-duration-calculator", title: "Time Duration", description: "Add or subtract hours and minutes.", category: "Date & Time", icon: Timer },
  { slug: "fuel-cost-calculator", title: "Fuel Cost", description: "Plan the fuel cost of your next trip.", category: "Everyday", icon: Fuel },
  { slug: "electricity-cost-calculator", title: "Electricity Cost", description: "Estimate the cost of running appliances.", category: "Everyday", icon: Zap },
  { slug: "split-bill-calculator", title: "Split Bill", description: "Split a bill fairly with friends.", category: "Shopping", icon: Utensils },
  { slug: "percentage-points-calculator", title: "Percentage Points", description: "Compare two percentages clearly.", category: "Math", icon: BadgePercent },
];
const CATEGORIES = ["All", "Money", "Health", "Shopping", "Date & Time", "Math", "Conversion", "Everyday"];

function useTheme() {
  const [dark, setDark] = useState(() => {
    const saved = localStorage.getItem("cn-theme");
    return saved ? saved === "dark" : window.matchMedia?.("(prefers-color-scheme: dark)").matches ?? false;
  });
  useEffect(() => { document.documentElement.classList.toggle("dark", dark); localStorage.setItem("cn-theme", dark ? "dark" : "light"); }, [dark]);
  return [dark, () => setDark((v) => !v)] as const;
}
function useLocalList(key: string) {
  const [items, setItems] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem(key) || "[]"); } catch { return []; } });
  const save = (next: string[]) => { setItems(next); localStorage.setItem(key, JSON.stringify(next)); };
  return [items, save] as const;
}
function useMeta(title: string, description: string) {
  useEffect(() => { document.title = `${title} · CalcNova`; let meta = document.querySelector('meta[name="description"]'); if (!meta) { meta = document.createElement("meta"); meta.setAttribute("name", "description"); document.head.appendChild(meta); } meta.setAttribute("content", description); }, [title, description]);
}

function Header() {
  const [dark, toggle] = useTheme();
  const [location] = useLocation();
  const [open, setOpen] = useState(false);
  return <header className="cn-header"><div className="cn-container cn-header-inner">
    <Link href="/" className="cn-logo" data-testid="link-logo"><span className="cn-mark">N</span> CalcNova</Link>
    <nav className="cn-nav" aria-label="Primary navigation">
      <Link href="/calculator" className={location.startsWith("/calculator") ? "active" : ""} data-testid="link-calculators">Calculators</Link>
      <Link href="/calculator?category=Health" className={location.includes("category=Health") ? "active" : ""}>Categories</Link>
      <Link href="/about" className={location === "/about" ? "active" : ""} data-testid="link-about">About</Link>
      <Link href="/contact" className={location === "/contact" ? "active" : ""} data-testid="link-contact">Contact</Link>
    </nav>
    <div className="cn-header-actions">
      <button className="cn-icon-btn" onClick={toggle} aria-label={dark ? "Use light theme" : "Use dark theme"} data-testid="button-theme">{dark ? <Sun size={18} /> : <Moon size={18} />}</button>
      <button className="cn-icon-btn" onClick={() => setOpen(!open)} aria-label="Toggle menu" data-testid="button-menu"><Menu size={19} /></button>
    </div>
    {open && <div className="cn-menu-popover"><Link href="/calculator" onClick={() => setOpen(false)} data-testid="menu-calculators">All calculators</Link><Link href="/privacy" onClick={() => setOpen(false)} data-testid="menu-privacy">Privacy policy</Link><Link href="/terms" onClick={() => setOpen(false)} data-testid="menu-terms">Terms</Link><Link href="/about" onClick={() => setOpen(false)}>Why CalcNova</Link></div>}
  </div></header>;
}
function MobileNav() {
  const [location] = useLocation();
  return <nav className="cn-mobile-nav" aria-label="Mobile navigation"><Link href="/" className={location === "/" ? "active" : ""} data-testid="mobile-home"><HomeIcon size={18} /><span>Home</span></Link><Link href="/calculator" className={location.startsWith("/calculator") ? "active" : ""} data-testid="mobile-calculators"><Calculator size={18} /><span>All tools</span></Link><Link href="/calculator?category=Health" className={location.includes("category=Health") ? "active" : ""}><HeartPulse size={18} /><span>Categories</span></Link><Link href="/about" className={location === "/about" ? "active" : ""} data-testid="mobile-about"><Info size={18} /><span>About</span></Link></nav>;
}
function Footer() {
  return <footer className="cn-footer"><div className="cn-container cn-footer-inner"><span>CalcNova is free to use. · © 2026 CalcNova.</span><span className="cn-footer-links"><Link href="/privacy" data-testid="link-privacy">Privacy</Link><Link href="/terms" data-testid="link-terms">Terms</Link><Link href="/contact" data-testid="link-footer-contact">Contact</Link></span></div></footer>;
}
function Shell({ children }: { children: ReactNode }) { return <div className="cn-shell"><Header /><main className="cn-main">{children}</main><Footer /><MobileNav /></div>; }
function Ad() { return <div className="cn-ad" aria-label="Advertisement">Advertisement</div>; }
function SectionLabel({ children }: { children: ReactNode }) { return <span className="cn-kicker">{children}</span>; }
function CalcCard({ calc, favorite, onFavorite }: { calc: Calc; favorite: boolean; onFavorite: () => void }) {
  const Icon = calc.icon;
  return <div className="cn-calc-card" data-testid={`card-calculator-${calc.slug}`}><Link href={`/calculator/${calc.slug}`} style={{ display: "flex", flexDirection: "column", flex: 1 }} data-testid={`link-calculator-${calc.slug}`}><span className="cn-card-icon"><Icon size={19} /></span><span style={{ marginTop: "auto" }}><h3>{calc.title}</h3><p>{calc.description}</p></span></Link><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><span className="cn-kicker" style={{ fontSize: ".58rem" }}>{calc.category}</span><button className="cn-icon-btn" style={{ width: 30, height: 30, border: 0 }} onClick={onFavorite} aria-label={favorite ? `Remove ${calc.title} from favorites` : `Favorite ${calc.title}`} data-testid={`button-favorite-${calc.slug}`}><Star size={16} fill={favorite ? "currentColor" : "none"} /></button></div></div>;
}
function getRecommended(calc: Calc) {
  const sameCategory = CALCS.filter((item) => item.category === calc.category && item.slug !== calc.slug);
  return sameCategory[0] || CALCS[(CALCS.findIndex((item) => item.slug === calc.slug) + 1) % CALCS.length];
}

function Home() {
  useMeta("Every calculation you need", "CalcNova is the private, fast, offline-friendly home for everyday calculations.");
  const [favorites, setFavorites] = useLocalList("cn-favorites");
  const [homeQuery, setHomeQuery] = useState("");
  const toggleFav = (slug: string) => setFavorites(favorites.includes(slug) ? favorites.filter((x) => x !== slug) : [...favorites, slug]);
  const matching = homeQuery.trim() ? CALCS.filter((calc) => `${calc.title} ${calc.description} ${calc.category}`.toLowerCase().includes(homeQuery.toLowerCase())).slice(0, 4) : [];
  return <Shell><div className="cn-container">
    <section className="cn-hero"><div><div className="cn-hero-badge"><Sparkles size={14} /> Built for quick wins</div><SectionLabel>Every calculation you need, in one place.</SectionLabel><h1 className="cn-display">All Your Calculations.<br /><span style={{ color: "hsl(var(--primary))" }}>One Simple Place.</span></h1><p>CalcNova keeps the useful stuff close: money, health, shopping, dates, math, and conversions. No account. No noise. Just a confident answer when you need one.</p><div className="cn-hero-actions"><Link href="/calculator" className="cn-button cn-button-primary" data-testid="button-explore">Explore all tools <ArrowRight size={16} /></Link><Link href="/about" className="cn-button cn-button-ghost" data-testid="button-about">Why CalcNova</Link></div><div className="cn-home-search"><Search size={18} /><input aria-label="Search any calculator" value={homeQuery} onChange={(e) => setHomeQuery(e.target.value)} placeholder="Search anything: EMI, BMI, tip..." /><Link href={`/calculator${homeQuery ? `?q=${encodeURIComponent(homeQuery)}` : ""}`} className="cn-search-go">Find it <ArrowRight size={14} /></Link>{matching.length > 0 && <div className="cn-home-search-results">{matching.map((calc) => <Link key={calc.slug} href={`/calculator/${calc.slug}`} onClick={() => setHomeQuery("")}><span>{calc.title}</span><small>{calc.category}</small></Link>)}</div>}</div></div><div className="cn-orbit"><div className="cn-orbit-card"><div className="cn-orbit-line"><span>Quick calculation</span><span className="cn-kicker" style={{ fontSize: ".6rem" }}>ready</span></div><div className="cn-orbit-result cn-mono">₹ 48,720.00</div><div className="cn-orbit-line"><span>Monthly investment</span><strong style={{ color: "hsl(var(--accent))" }}>+ 12.4%</strong></div><div className="cn-chart">{[30, 45, 38, 58, 51, 78, 94].map((h, i) => <span className="cn-bar" style={{ height: `${h}%`, animationDelay: `${i * .08}s` }} key={i} />)}</div></div></div></section>
    <Ad />
    <section className="cn-section cn-category-strip"><div className="cn-section-head"><div><SectionLabel>Pick your lane</SectionLabel><h2 className="cn-display">Every category, right here.</h2><p className="cn-section-intro">Tap a vibe and get the whole toolbox. Nothing is hidden three menus deep.</p></div></div><div className="cn-category-pills">{CATEGORIES.slice(1).map((category) => <Link key={category} href={`/calculator?category=${encodeURIComponent(category)}`} className="cn-category-pill"><span>{category}</span><small>{CALCS.filter((calc) => calc.category === category).length} tools</small><ChevronRight size={15} /></Link>)}</div></section>
    <section className="cn-section" style={{ paddingTop: 18 }}><div className="cn-section-head"><div><SectionLabel>All the tools</SectionLabel><h2 className="cn-display">Pick one. Get moving.</h2></div><span className="cn-tool-count">{CALCS.length} calculators</span></div>{CATEGORIES.slice(1).map((category) => <div className="cn-home-category" key={category}><div className="cn-home-category-heading"><h3>{category} calculators</h3><Link href={`/calculator?category=${encodeURIComponent(category)}`}>See all <ArrowRight size={14} /></Link></div><div className="cn-grid">{CALCS.filter((calc) => calc.category === category).map((calc) => <CalcCard key={calc.slug} calc={calc} favorite={favorites.includes(calc.slug)} onFavorite={() => toggleFav(calc.slug)} />)}</div></div>)}</section>
    <section className="cn-section" style={{ paddingTop: 12 }}><div className="cn-section-head"><div><SectionLabel>Why it sticks</SectionLabel><h2 className="cn-display">Clear by design.</h2></div></div><div className="cn-trust"><div className="cn-trust-item"><ShieldCheck size={21} color="hsl(var(--accent))" /><strong>Private by default</strong><span>Your inputs stay in this browser. CalcNova works without accounts or servers.</span></div><div className="cn-trust-item"><RotateCcw size={21} color="hsl(var(--accent))" /><strong>Ready when offline</strong><span>Bookmark the tools you use and keep calculating after the connection disappears.</span></div><div className="cn-trust-item"><Star size={21} color="hsl(var(--accent))" /><strong>Results with context</strong><span>Every answer comes with labels, formulas, and the small detail that builds trust.</span></div></div></section>
  </div></Shell>;
}

function Directory() {
  useMeta("Calculator directory", "Browse every CalcNova calculator by category.");
  const [location] = useLocation();
  const params = new URLSearchParams(location.split("?")[1] || "");
  const [query, setQuery] = useState(params.get("q") || ""); const [category, setCategory] = useState(params.get("category") || "All"); const [favorites, setFavorites] = useLocalList("cn-favorites");
  const results = useMemo(() => CALCS.filter((c) => (category === "All" || c.category === category) && `${c.title} ${c.description}`.toLowerCase().includes(query.toLowerCase())), [query, category]);
  const toggle = (slug: string) => setFavorites(favorites.includes(slug) ? favorites.filter((x) => x !== slug) : [...favorites, slug]);
  const recommended = results[0] || CALCS.find((calc) => calc.category === "Everyday") || CALCS[0];
  return <Shell><div className="cn-container"><div className="cn-page-title"><div className="cn-hero-badge"><Sparkles size={14} /> {CALCS.length} tools, zero signup</div><SectionLabel>CalcNova directory</SectionLabel><h1 className="cn-display">Find your next<br /><span style={{ color: "hsl(var(--primary))" }}>answer.</span></h1><p>One focused tool for every ordinary question. Search by what you want to solve, not by what the formula is called.</p></div><div className="cn-search"><Search size={19} /><label className="cn-sr-only" htmlFor="calculator-search">Search calculators</label><input id="calculator-search" type="search" placeholder="Try “loan”, “height”, or “tip”" value={query} onChange={(e) => setQuery(e.target.value)} data-testid="input-calculator-search" /></div><div className="cn-recommendation"><div><span className="cn-kicker">You might also like</span><strong>{recommended.title}</strong><p>{recommended.description}</p></div><Link href={`/calculator/${recommended.slug}`} className="cn-button cn-button-soft">Open tool <ArrowRight size={15} /></Link></div><div className="cn-category-tabs" aria-label="Calculator categories">{CATEGORIES.map((c) => <button key={c} className={`cn-chip ${category === c ? "active" : ""}`} onClick={() => setCategory(c)} data-testid={`button-category-${c.toLowerCase().replace(/\W/g, "-")}`}>{c}<span>{c === "All" ? CALCS.length : CALCS.filter((calc) => calc.category === c).length}</span></button>)}</div><div className="cn-directory-layout"><aside><div className="cn-kicker" style={{ marginBottom: 10 }}>Browse by category</div><div className="cn-categories">{CATEGORIES.map((c) => <button key={c} className={`cn-chip ${category === c ? "active" : ""}`} onClick={() => setCategory(c)}>{c}<span>{c === "All" ? CALCS.length : CALCS.filter((calc) => calc.category === c).length}</span></button>)}</div><div className="cn-side-note"><HeartPulse size={17} /><strong>Health tools?</strong><span>Tap Health to see every wellness calculator together.</span></div></aside><section><div className="cn-section-head" style={{ marginBottom: 15 }}><span style={{ color: "hsl(var(--muted-foreground))", fontSize: ".8rem" }}>{results.length} {results.length === 1 ? "calculator" : "calculators"}</span><span className="cn-mono" style={{ color: "hsl(var(--muted-foreground))", fontSize: ".7rem" }}>LOCAL / PRIVATE</span></div>{results.length ? <div className="cn-grid">{results.map((calc) => <CalcCard key={calc.slug} calc={calc} favorite={favorites.includes(calc.slug)} onFavorite={() => toggle(calc.slug)} />)}</div> : <div className="cn-empty" style={{ border: "1px dashed hsl(var(--border))", borderRadius: 16 }}><Search size={26} style={{ marginBottom: 10 }} /><div>No calculators match that search.</div><button className="cn-button cn-button-soft" style={{ marginTop: 14 }} onClick={() => { setQuery(""); setCategory("All"); }} data-testid="button-clear-search">Clear search</button></div>}</section></div></div></Shell>;
}

function Field({ label, value, onChange, type = "number", placeholder, min, step = "any" }: { label: string; value: string; onChange: (v: string) => void; type?: string; placeholder?: string; min?: string; step?: string }) {
  return <div className="cn-field"><label>{label}</label><input className="cn-input" type={type} value={value} min={min} step={step} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} data-testid={`input-${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`} /></div>;
}
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: { value: string; label: string }[] }) {
  return <div className="cn-field"><label>{label}</label><select className="cn-select" value={value} onChange={(e) => onChange(e.target.value)} data-testid={`select-${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`}>{options.map((o) => <option value={o.value} key={o.value}>{o.label}</option>)}</select></div>;
}
function Result({ label, value, rows = [], note, formula }: { label: string; value: string; rows?: [string, string][]; note?: string; formula?: string }) {
  const copy = () => navigator.clipboard?.writeText(value);
  return <div className="cn-result-panel"><div className="cn-result-kicker">{label}</div><div className="cn-result-value" data-testid="text-result">{value}</div><div className="cn-breakdown">{rows.map(([a, b]) => <div className="cn-breakdown-row" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>{formula && <div className="cn-formula">Formula: {formula}</div>}{note && <div className="cn-note">{note}</div>}<button className="cn-button cn-button-ghost" style={{ marginTop: 18, width: "100%" }} onClick={copy} data-testid="button-copy-result"><Copy size={15} /> Copy result</button></div>;
}
function Frame({ calc, children, result, onReset }: { calc: Calc; children: ReactNode; result: ReactNode; onReset: () => void }) {
  useMeta(calc.title, calc.description); const [history, setHistory] = useLocalList("cn-history");
  useEffect(() => { if (calc.slug && !history.includes(calc.slug)) setHistory([calc.slug, ...history].slice(0, 8)); }, [calc.slug]);
  const recommended = getRecommended(calc);
  return <Shell><div className="cn-container"><div className="cn-page-title" style={{ paddingBottom: 22 }}><div className="cn-breadcrumbs"><Link href="/calculator" className="cn-back-link" data-testid="link-back-directory"><ArrowLeft size={15} /> Back to all calculators</Link><span>/</span><span>{calc.category}</span></div><h1 className="cn-display">{calc.title}</h1><p>{calc.description} Results are calculated locally in your browser.</p></div><Ad /><div className="cn-form-layout" style={{ marginTop: 24 }}><div className="cn-calculator-panel"><div className="cn-panel-head"><div><div className="cn-kicker">{calc.category}</div><h2>Enter your details</h2></div><button className="cn-icon-btn" onClick={onReset} aria-label="Reset calculator" data-testid="button-reset"><RotateCcw size={17} /></button></div>{children}</div>{result}</div><div className="cn-next-tool"><div><span className="cn-kicker">Keep the momentum</span><strong>Next up: {recommended.title}</strong><p>{recommended.description}</p></div><Link href={`/calculator/${recommended.slug}`} className="cn-button cn-button-primary">Try next <ArrowRight size={15} /></Link></div></div></Shell>;
}
const n = (v: string) => Number(v) || 0;
function Basic() {
  const calc = CALCS[0]; const [expr, setExpr] = useState(""); const [answer, setAnswer] = useState("0"); const [error, setError] = useState("");
  const press = (key: string) => { setError(""); if (key === "C") { setExpr(""); setAnswer("0"); return; } if (key === "⌫") { setExpr((x) => x.slice(0, -1)); return; } if (key === "=") { try { const sanitized = expr.replace(/%/g, "/100").replace(/[^0-9+\-*/().\s]/g, ""); if (!sanitized || !/[0-9)]/.test(sanitized)) throw new Error(); const value = Function(`"use strict"; return (${sanitized})`)(); if (!Number.isFinite(value)) throw new Error(); setAnswer(String(Number(value.toFixed(10)))); } catch { setError("Check the expression and try again."); setAnswer("—"); } return; } setExpr((x) => x + key); };
  useEffect(() => { const handler = (e: KeyboardEvent) => { if (/^[0-9+\-*/().%]$/.test(e.key)) press(e.key); else if (e.key === "Enter" || e.key === "=") press("="); else if (e.key === "Backspace") press("⌫"); else if (e.key === "Escape") press("C"); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); });
  const keys = ["C", "(", ")", "⌫", "7", "8", "9", "/", "4", "5", "6", "*", "1", "2", "3", "-", "0", ".", "%", "+"];
  return <Frame calc={calc} onReset={() => { setExpr(""); setAnswer("0"); setError(""); }} result={<Result label="Answer" value={answer} note={error || "Tip: use your keyboard, parentheses, and % for quick calculations."} formula="numbers and operators, evaluated safely" />}><div className="cn-calc-display"><div className="cn-calc-expression">{expr || "Ready"}</div><div className="cn-calc-answer" data-testid="text-basic-answer">{answer}</div></div><div className="cn-calc-keypad">{keys.map((key) => <button key={key} className={`cn-key ${/[/*+—-]/.test(key) ? "operator" : ""}`} onClick={() => press(key)} data-testid={`button-key-${key === "⌫" ? "backspace" : key}`}>{key}</button>)}<button className="cn-key equals" style={{ gridColumn: "span 4" }} onClick={() => press("=")} data-testid="button-equals">Calculate</button></div></Frame>;
}
function Percentage() {
  const calc = CALCS[1]; const [mode, setMode] = useState("of"); const [a, setA] = useState("25"); const [b, setB] = useState("240");
  const value = mode === "of" ? n(a) * n(b) / 100 : mode === "change" ? (n(b) ? ((n(a) - n(b)) / n(b)) * 100 : 0) : (n(b) ? (n(a) / n(b)) * 100 : 0);
  const labels = mode === "of" ? ["What is the percentage?", "Percentage", "Value"] : mode === "change" ? ["New value", "Original value"] : ["Part", "Whole"];
  return <Frame calc={calc} onReset={() => { setA(""); setB(""); }} result={<Result label={mode === "of" ? "Result" : "Percentage"} value={`${value.toFixed(2)}${mode === "of" ? "" : "%"}`} rows={mode === "of" ? [["Calculation", `${a}% of ${b}`]] : []} formula={mode === "of" ? "percentage ÷ 100 × value" : mode === "change" ? "(new − original) ÷ original × 100" : "part ÷ whole × 100"} />}><div className="cn-toggle-row"><button className={`cn-toggle ${mode === "of" ? "active" : ""}`} onClick={() => setMode("of")} data-testid="button-mode-of">Percentage of</button><button className={`cn-toggle ${mode === "change" ? "active" : ""}`} onClick={() => setMode("change")} data-testid="button-mode-change">Percentage change</button><button className={`cn-toggle ${mode === "ratio" ? "active" : ""}`} onClick={() => setMode("ratio")} data-testid="button-mode-ratio">What percent?</button></div><div className="cn-field-grid two" style={{ marginTop: 20 }}><Field label={labels[0]} value={a} onChange={setA} /><Field label={labels[1]} value={b} onChange={setB} /></div></Frame>;
}
function EMI() { const calc = CALCS[2]; const [p, setP] = useState("250000"); const [r, setR] = useState("8.5"); const [y, setY] = useState("20"); const months = n(y) * 12; const rate = n(r) / 1200; const emi = rate ? n(p) * rate * Math.pow(1 + rate, months) / (Math.pow(1 + rate, months) - 1) : months ? n(p) / months : 0; const total = emi * months; return <Frame calc={calc} onReset={() => { setP(""); setR(""); setY(""); }} result={<Result label="Monthly EMI" value={`₹ ${emi.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`} rows={[["Principal", `₹ ${n(p).toLocaleString("en-IN")}`], ["Total interest", `₹ ${Math.max(0, total - n(p)).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`], ["Total repayment", `₹ ${total.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`]]} formula="P × r × (1+r)^n ÷ ((1+r)^n − 1)" />}><div className="cn-field-grid"><Field label="Loan amount" value={p} onChange={setP} /><Field label="Annual interest rate (%)" value={r} onChange={setR} /><Field label="Loan tenure (years)" value={y} onChange={setY} /></div></Frame>; }
function SIP() { const calc = CALCS[3]; const [p, setP] = useState("10000"); const [r, setR] = useState("12"); const [y, setY] = useState("10"); const m = n(y) * 12; const i = n(r) / 1200; const fv = i ? n(p) * ((Math.pow(1 + i, m) - 1) / i) * (1 + i) : n(p) * m; const invested = n(p) * m; return <Frame calc={calc} onReset={() => { setP(""); setR(""); setY(""); }} result={<Result label="Estimated value" value={`₹ ${fv.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`} rows={[["Invested amount", `₹ ${invested.toLocaleString("en-IN")}`], ["Estimated returns", `₹ ${Math.max(0, fv - invested).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`]]} formula="P × ((1+i)^n − 1) ÷ i × (1+i)" />}><div className="cn-field-grid"><Field label="Monthly investment" value={p} onChange={setP} /><Field label="Expected return (% p.a.)" value={r} onChange={setR} /><Field label="Time period (years)" value={y} onChange={setY} /></div><div className="cn-chart">{[.38, .47, .56, .65, .73, .84, 1].map((h, i2) => <span className="cn-bar" key={i2} style={{ height: `${h * 100}%`, animationDelay: `${i2 * .08}s` }} />)}</div></Frame>; }
function GST() { const calc = CALCS[4]; const [amount, setAmount] = useState("1000"); const [rate, setRate] = useState("18"); const [mode, setMode] = useState("add"); const tax = n(amount) * n(rate) / 100; const total = mode === "add" ? n(amount) + tax : n(amount); const base = mode === "add" ? n(amount) : n(amount) / (1 + n(rate) / 100); const gst = mode === "add" ? tax : n(amount) - base; return <Frame calc={calc} onReset={() => { setAmount(""); setRate("18"); }} result={<Result label={mode === "add" ? "Price with GST" : "Price before GST"} value={`₹ ${total === 0 ? "0" : (mode === "add" ? total : base).toFixed(2)}`} rows={[["Base amount", `₹ ${base.toFixed(2)}`], ["GST amount", `₹ ${gst.toFixed(2)}`], ["GST rate", `${rate}%`]]} formula={mode === "add" ? "amount + (amount × rate ÷ 100)" : "inclusive price ÷ (1 + rate)"}/>}><div className="cn-toggle-row"><button className={`cn-toggle ${mode === "add" ? "active" : ""}`} onClick={() => setMode("add")} data-testid="button-gst-add">Add GST</button><button className={`cn-toggle ${mode === "remove" ? "active" : ""}`} onClick={() => setMode("remove")} data-testid="button-gst-remove">Remove GST</button></div><div className="cn-field-grid two" style={{ marginTop: 20 }}><Field label="Amount" value={amount} onChange={setAmount} /><Field label="GST rate (%)" value={rate} onChange={setRate} /></div><div className="cn-toggle-row" style={{ marginTop: 15 }}>{["5", "12", "18", "28"].map((x) => <button className="cn-toggle" key={x} onClick={() => setRate(x)} data-testid={`button-gst-rate-${x}`}>{x}%</button>)}</div></Frame>; }
function Discount() { const calc = CALCS[5]; const [price, setPrice] = useState("2499"); const [discount, setDiscount] = useState("20"); const [gst, setGst] = useState(""); const after = n(price) * (1 - n(discount) / 100); const tax = after * n(gst) / 100; return <Frame calc={calc} onReset={() => { setPrice(""); setDiscount(""); setGst(""); }} result={<Result label="You pay" value={`₹ ${(after + tax).toFixed(2)}`} rows={[["Original price", `₹ ${n(price).toFixed(2)}`], ["You save", `₹ ${(n(price) - after).toFixed(2)}`], ["GST", gst ? `₹ ${tax.toFixed(2)}` : "Not added"]]} formula="price × (1 − discount ÷ 100) + GST" />}><div className="cn-field-grid"><Field label="Original price" value={price} onChange={setPrice} /><Field label="Discount (%)" value={discount} onChange={setDiscount} /><Field label="Optional GST (%)" value={gst} onChange={setGst} placeholder="Leave blank if none" /></div></Frame>; }
function Age() { const calc = CALCS[6]; const [dob, setDob] = useState("1995-06-15"); const birth = new Date(`${dob}T00:00:00`); const now = new Date(); const valid = Number.isFinite(birth.getTime()); let years = valid ? now.getFullYear() - birth.getFullYear() : 0; let months = valid ? now.getMonth() - birth.getMonth() : 0; let days = valid ? now.getDate() - birth.getDate() : 0; if (days < 0) { months--; days += new Date(now.getFullYear(), now.getMonth(), 0).getDate(); } if (months < 0) { years--; months += 12; } const totalDays = valid ? Math.max(0, Math.floor((now.getTime() - birth.getTime()) / 86400000)) : 0; const next = valid ? new Date(now.getFullYear(), birth.getMonth(), birth.getDate()) : now; if (next < now) next.setFullYear(now.getFullYear() + 1); const until = valid ? Math.max(0, Math.ceil((next.getTime() - now.getTime()) / 86400000)) : 0; return <Frame calc={calc} onReset={() => setDob("")} result={<Result label="Your age" value={valid ? `${Math.max(0, years)}y ${Math.max(0, months)}m ${Math.max(0, days)}d` : "Enter a date"} rows={[["Total days lived", totalDays.toLocaleString()], ["Next birthday", valid ? `${until} days away` : "—"]]} note="Age is calculated from your local date and time." />}><Field label="Date of birth" type="date" value={dob} onChange={setDob} /></Frame>; }
function BMI() { const calc = CALCS[7]; const [unit, setUnit] = useState("metric"); const [height, setHeight] = useState("175"); const [inches, setInches] = useState(""); const [weight, setWeight] = useState("70"); const cm = unit === "metric" ? n(height) : n(height) * 30.48 + n(inches) * 2.54; const kg = unit === "metric" ? n(weight) : n(weight) * .453592; const bmi = cm ? kg / Math.pow(cm / 100, 2) : 0; const range = bmi < 18.5 ? "Underweight" : bmi < 25 ? "Healthy range" : bmi < 30 ? "Overweight" : "Obesity range"; return <Frame calc={calc} onReset={() => { setHeight(""); setWeight(""); setInches(""); }} result={<Result label="BMI" value={bmi ? bmi.toFixed(1) : "0"} rows={[["Category", range], ["Height", `${cm.toFixed(1)} cm`], ["Weight", `${kg.toFixed(1)} kg`]]} note="BMI is a screening measure, not a diagnosis." formula="weight (kg) ÷ height² (m)" />}><div className="cn-toggle-row"><button className={`cn-toggle ${unit === "metric" ? "active" : ""}`} onClick={() => setUnit("metric")} data-testid="button-bmi-metric">Centimetres / kg</button><button className={`cn-toggle ${unit === "imperial" ? "active" : ""}`} onClick={() => setUnit("imperial")} data-testid="button-bmi-imperial">Feet & inches / lb</button></div><div className="cn-field-grid two" style={{ marginTop: 20 }}><Field label={unit === "metric" ? "Height (cm)" : "Height (ft)"} value={height} onChange={setHeight} /><Field label={unit === "imperial" ? "Height (in)" : "Weight (kg)"} value={unit === "imperial" ? inches : weight} onChange={unit === "imperial" ? setInches : setWeight} />{unit === "imperial" && <Field label="Weight (lb)" value={weight} onChange={setWeight} />}</div></Frame>; }
function BMR() { const calc = CALCS[8]; const [sex, setSex] = useState("female"); const [age, setAge] = useState("30"); const [height, setHeight] = useState("170"); const [weight, setWeight] = useState("65"); const [activity, setActivity] = useState("1.375"); const bmr = sex === "male" ? 10 * n(weight) + 6.25 * n(height) - 5 * n(age) + 5 : 10 * n(weight) + 6.25 * n(height) - 5 * n(age) - 161; const tdee = bmr * n(activity); return <Frame calc={calc} onReset={() => { setAge(""); setHeight(""); setWeight(""); }} result={<Result label="Daily calorie estimate" value={`${Math.round(tdee).toLocaleString()} kcal`} rows={[["Basal metabolic rate", `${Math.round(bmr).toLocaleString()} kcal`], ["Activity multiplier", activity], ["Weekly estimate", `${Math.round(tdee * 7).toLocaleString()} kcal`]]} formula="Mifflin–St Jeor × activity level" />}><div className="cn-toggle-row"><button className={`cn-toggle ${sex === "female" ? "active" : ""}`} onClick={() => setSex("female")} data-testid="button-bmr-female">Female</button><button className={`cn-toggle ${sex === "male" ? "active" : ""}`} onClick={() => setSex("male")} data-testid="button-bmr-male">Male</button></div><div className="cn-field-grid two" style={{ marginTop: 20 }}><Field label="Age (years)" value={age} onChange={setAge} /><Field label="Height (cm)" value={height} onChange={setHeight} /><Field label="Weight (kg)" value={weight} onChange={setWeight} /><SelectField label="Activity level" value={activity} onChange={setActivity} options={[{ value: "1.2", label: "Sedentary" }, { value: "1.375", label: "Lightly active" }, { value: "1.55", label: "Moderately active" }, { value: "1.725", label: "Very active" }, { value: "1.9", label: "Extra active" }]} /></div></Frame>; }
function Interest({ compound = false }: { compound?: boolean }) { const calc = CALCS[compound ? 10 : 9]; const [p, setP] = useState("50000"); const [r, setR] = useState("8"); const [t, setT] = useState("5"); const [frequency, setFrequency] = useState("12"); const interest = compound ? n(p) * Math.pow(1 + n(r) / 100 / n(frequency), n(frequency) * n(t)) - n(p) : n(p) * n(r) / 100 * n(t); const total = n(p) + interest; return <Frame calc={calc} onReset={() => { setP(""); setR(""); setT(""); }} result={<Result label="Total amount" value={`₹ ${total.toLocaleString("en-IN", { maximumFractionDigits: 2 })}`} rows={[["Principal", `₹ ${n(p).toLocaleString("en-IN")}`], ["Interest earned", `₹ ${interest.toLocaleString("en-IN", { maximumFractionDigits: 2 })}`]]} formula={compound ? "P(1 + r/n)^(nt)" : "P × r × t ÷ 100"} />}><div className="cn-field-grid"><Field label="Principal" value={p} onChange={setP} /><Field label="Annual rate (%)" value={r} onChange={setR} /><Field label="Time (years)" value={t} onChange={setT} />{compound && <SelectField label="Compounding frequency" value={frequency} onChange={setFrequency} options={[{ value: "1", label: "Annually" }, { value: "2", label: "Half-yearly" }, { value: "4", label: "Quarterly" }, { value: "12", label: "Monthly" }, { value: "365", label: "Daily" }]} />}</div></Frame>; }
function Tip() { const calc = CALCS[11]; const [bill, setBill] = useState("1800"); const [tip, setTip] = useState("15"); const [people, setPeople] = useState("2"); const tipAmount = n(bill) * n(tip) / 100; return <Frame calc={calc} onReset={() => { setBill(""); setTip("15"); setPeople("2"); }} result={<Result label="Per person" value={`₹ ${((n(bill) + tipAmount) / Math.max(1, n(people))).toFixed(2)}`} rows={[["Tip amount", `₹ ${tipAmount.toFixed(2)}`], ["Total bill", `₹ ${(n(bill) + tipAmount).toFixed(2)}`], ["People", people || "1"]]} formula="(bill + tip) ÷ people" />}><div className="cn-field-grid"><Field label="Bill amount" value={bill} onChange={setBill} /><Field label="Tip (%)" value={tip} onChange={setTip} /><Field label="Number of people" value={people} onChange={setPeople} min="1" /></div><div className="cn-toggle-row" style={{ marginTop: 16 }}>{["10", "15", "18", "20"].map((x) => <button className="cn-toggle" key={x} onClick={() => setTip(x)} data-testid={`button-tip-${x}`}>{x}%</button>)}</div></Frame>; }
function Salary() { const calc = CALCS[12]; const [annual, setAnnual] = useState("1200000"); const [tax, setTax] = useState("10"); const [deductions, setDeductions] = useState("24000"); const monthly = n(annual) / 12; const taxAmount = monthly * n(tax) / 100; const net = monthly - taxAmount - n(deductions) / 12; return <Frame calc={calc} onReset={() => { setAnnual(""); setTax("10"); setDeductions("24000"); }} result={<Result label="Estimated monthly take-home" value={`₹ ${net.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`} rows={[["Gross monthly", `₹ ${monthly.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`], ["Estimated tax", `₹ ${taxAmount.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`], ["Monthly deductions", `₹ ${(n(deductions) / 12).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`]]} note="An estimate for planning, not a payroll statement." />}><div className="cn-field-grid"><Field label="Annual salary" value={annual} onChange={setAnnual} /><Field label="Estimated tax (%)" value={tax} onChange={setTax} /><Field label="Annual deductions" value={deductions} onChange={setDeductions} /></div></Frame>; }
function DateDiff() { const calc = CALCS[13]; const [from, setFrom] = useState("2024-01-01"); const [to, setTo] = useState("2026-01-01"); const a = new Date(`${from}T00:00:00`), b = new Date(`${to}T00:00:00`); const days = Number.isFinite(a.getTime()) && Number.isFinite(b.getTime()) ? Math.abs(Math.round((b.getTime() - a.getTime()) / 86400000)) : 0; const earlier = a <= b ? from : to; const later = a <= b ? to : from; return <Frame calc={calc} onReset={() => { setFrom(""); setTo(""); }} result={<Result label="Difference" value={`${days.toLocaleString()} days`} rows={[["Approximate weeks", (days / 7).toFixed(1)], ["Approximate months", (days / 30.4375).toFixed(1)], ["From", earlier || "—"], ["To", later || "—"]]} note="Leap years and calendar dates are handled by your browser's date engine." />}><div className="cn-field-grid two"><Field label="Start date" type="date" value={from} onChange={setFrom} /><Field label="End date" type="date" value={to} onChange={setTo} /></div></Frame>; }
function Converter() { const calc = CALCS[14]; const [kind, setKind] = useState("length"); const [value, setValue] = useState("1"); const [from, setFrom] = useState("kilometre"); const [to, setTo] = useState("mile"); const units: Record<string, { value: string; label: string; factor: number }[]> = { length: [{ value: "metre", label: "Metres", factor: 1 }, { value: "kilometre", label: "Kilometres", factor: 1000 }, { value: "mile", label: "Miles", factor: 1609.344 }, { value: "foot", label: "Feet", factor: .3048 }], weight: [{ value: "gram", label: "Grams", factor: 1 }, { value: "kilogram", label: "Kilograms", factor: 1000 }, { value: "pound", label: "Pounds", factor: 453.592 }], area: [{ value: "sqm", label: "Square metres", factor: 1 }, { value: "sqft", label: "Square feet", factor: .092903 }], volume: [{ value: "litre", label: "Litres", factor: 1 }, { value: "gallon", label: "US gallons", factor: 3.78541 }], speed: [{ value: "kph", label: "km/h", factor: 1 }, { value: "mph", label: "mph", factor: 1.60934 }], time: [{ value: "minute", label: "Minutes", factor: 1 }, { value: "hour", label: "Hours", factor: 60 }, { value: "day", label: "Days", factor: 1440 }], digital: [{ value: "kb", label: "Kilobytes", factor: 1 }, { value: "mb", label: "Megabytes", factor: 1024 }, { value: "gb", label: "Gigabytes", factor: 1048576 }], temperature: [{ value: "c", label: "Celsius", factor: 1 }, { value: "f", label: "Fahrenheit", factor: 1 }] }; const list = units[kind]; const result = kind === "temperature" ? (from === "c" && to === "f" ? n(value) * 9 / 5 + 32 : from === "f" && to === "c" ? (n(value) - 32) * 5 / 9 : n(value)) : n(value) * (list.find((u) => u.value === from)?.factor || 1) / (list.find((u) => u.value === to)?.factor || 1); useEffect(() => { setFrom(units[kind][0].value); setTo(units[kind][1].value); }, [kind]); return <Frame calc={calc} onReset={() => setValue("")} result={<Result label="Converted value" value={`${result.toLocaleString(undefined, { maximumFractionDigits: 6 })} ${list.find((u) => u.value === to)?.label || to}`} rows={[["Category", kind], ["Input", `${value || 0} ${list.find((u) => u.value === from)?.label || from}`]]} />}><SelectField label="Category" value={kind} onChange={setKind} options={[["length", "Length"], ["weight", "Weight"], ["temperature", "Temperature"], ["area", "Area"], ["volume", "Volume"], ["speed", "Speed"], ["time", "Time"], ["digital", "Digital storage"]].map(([value, label]) => ({ value, label }))} /><div className="cn-field-grid two" style={{ marginTop: 15 }}><Field label="Value" value={value} onChange={setValue} /><SelectField label="From" value={from} onChange={setFrom} options={list.map((u) => ({ value: u.value, label: u.label }))} /><SelectField label="To" value={to} onChange={setTo} options={list.map((u) => ({ value: u.value, label: u.label }))} /></div></Frame>; }
function Currency() { const calc = CALCS[15]; const [amount, setAmount] = useState("100"); const [from, setFrom] = useState("USD"); const [to, setTo] = useState("INR"); const [rates, setRates] = useState<Record<string, number>>(() => { try { return JSON.parse(localStorage.getItem("cn-rates") || '{"USD":1,"INR":83.2,"EUR":0.92,"GBP":0.79,"JPY":156.4}'); } catch { return { USD: 1, INR: 83.2, EUR: .92, GBP: .79, JPY: 156.4 }; } }); const result = n(amount) / (rates[from] || 1) * (rates[to] || 1); const updateRate = (currency: string, value: string) => { const next = { ...rates, [currency]: n(value) || 1 }; setRates(next); localStorage.setItem("cn-rates", JSON.stringify(next)); }; return <Frame calc={calc} onReset={() => setAmount("")} result={<Result label={`${to} amount`} value={`${result.toLocaleString(undefined, { maximumFractionDigits: 2 })} ${to}`} rows={[["Rate used", `1 ${from} = ${(rates[to] / rates[from]).toFixed(4)} ${to}`], ["Input", `${amount || 0} ${from}`]]} note="Rates are not live. Edit the reference rates below to match your preferred source." />}><div className="cn-field-grid two"><Field label="Amount" value={amount} onChange={setAmount} /><SelectField label="From currency" value={from} onChange={setFrom} options={Object.keys(rates).map((x) => ({ value: x, label: x }))} /><SelectField label="To currency" value={to} onChange={setTo} options={Object.keys(rates).map((x) => ({ value: x, label: x }))} /></div><div className="cn-history"><h3>Editable reference rates</h3>{Object.entries(rates).map(([currency, rate]) => <div className="cn-history-row" key={currency}><span>1 USD = {currency}</span><input className="cn-input" style={{ width: 115, minHeight: 34, textAlign: "right" }} type="number" value={rate} onChange={(e) => updateRate(currency, e.target.value)} data-testid={`input-rate-${currency}`} /></div>)}</div></Frame>; }

const calcFor = (slug: string) => CALCS.find((calc) => calc.slug === slug)!;
const gcd = (a: number, b: number): number => b ? gcd(b, a % b) : Math.abs(a) || 1;
const listNumbers = (value: string) => value.split(",").map((part) => Number(part.trim())).filter((part) => Number.isFinite(part));

function Fraction() {
  const calc = calcFor("fraction-calculator"); const [a, setA] = useState("1"); const [b, setB] = useState("2"); const [c, setC] = useState("1"); const [d, setD] = useState("4"); const [op, setOp] = useState("+");
  const left = n(a) / (n(b) || 1), right = n(c) / (n(d) || 1); const decimal = op === "+" ? left + right : op === "−" ? left - right : op === "×" ? left * right : right ? left / right : 0; const numerator = op === "+" ? n(a) * (n(d) || 1) + n(c) * (n(b) || 1) : op === "−" ? n(a) * (n(d) || 1) - n(c) * (n(b) || 1) : op === "×" ? n(a) * n(c) : n(a) * (n(d) || 1); const denominator = op === "÷" ? (n(b) || 1) * (n(c) || 1) : op === "×" ? (n(b) || 1) * (n(d) || 1) : (n(b) || 1) * (n(d) || 1); const divisor = gcd(Math.round(numerator), Math.round(denominator)); const fraction = `${Math.round(numerator / divisor)}/${Math.round(denominator / divisor)}`;
  return <Frame calc={calc} onReset={() => { setA(""); setB(""); setC(""); setD(""); }} result={<Result label="Simplified result" value={fraction} rows={[["Decimal", Number.isFinite(decimal) ? decimal.toFixed(4) : "Enter valid values"], ["Expression", `${a}/${b} ${op} ${c}/${d}`]]} formula="common denominator, then simplify by the greatest common divisor" />}><div className="cn-toggle-row"><span className="cn-kicker" style={{ alignSelf: "center" }}>Operation</span>{["+","−","×","÷"].map((item) => <button className={`cn-toggle ${op === item ? "active" : ""}`} key={item} onClick={() => setOp(item)}>{item}</button>)}</div><div className="cn-fraction-inputs"><div><Field label="Numerator" value={a} onChange={setA} /><div className="cn-fraction-line" /><Field label="Denominator" value={b} onChange={setB} /></div><span className="cn-fraction-op">{op}</span><div><Field label="Numerator" value={c} onChange={setC} /><div className="cn-fraction-line" /><Field label="Denominator" value={d} onChange={setD} /></div></div></Frame>;
}
function Average() {
  const calc = calcFor("average-calculator"); const [values, setValues] = useState("12, 18, 24, 30"); const nums = listNumbers(values); const total = nums.reduce((sum, value) => sum + value, 0); const average = nums.length ? total / nums.length : 0;
  return <Frame calc={calc} onReset={() => setValues("")} result={<Result label="Average" value={nums.length ? average.toFixed(2) : "Enter numbers"} rows={[["Total", total.toFixed(2)], ["Count", String(nums.length)], ["Range", nums.length ? `${Math.min(...nums)} – ${Math.max(...nums)}` : "—"]]} formula="sum of values ÷ number of values" />}><Field label="Numbers separated by commas" type="text" value={values} onChange={setValues} placeholder="12, 18, 24, 30" /></Frame>;
}
function Ratio() {
  const calc = calcFor("ratio-calculator"); const [a, setA] = useState("2"); const [b, setB] = useState("3"); const [part, setPart] = useState("10"); const scale = n(a) ? n(part) / n(a) : 0; const other = n(b) * scale; const divisor = gcd(Math.round(n(a)), Math.round(n(b)));
  return <Frame calc={calc} onReset={() => { setA(""); setB(""); setPart(""); }} result={<Result label="Scaled ratio" value={`${part || 0} : ${other.toFixed(2)}`} rows={[["Simplified ratio", `${Math.round(n(a) / divisor)} : ${Math.round(n(b) / divisor)}`], ["Scale factor", scale.toFixed(2)]]} formula="second part × (target first part ÷ first part)" />}><div className="cn-field-grid two"><Field label="First part" value={a} onChange={setA} /><Field label="Second part" value={b} onChange={setB} /><Field label="Target first part" value={part} onChange={setPart} /></div></Frame>;
}
function Scientific() {
  const calc = calcFor("scientific-calculator"); const [value, setValue] = useState("45"); const [operation, setOperation] = useState("sin"); const x = n(value); const answer = operation === "sin" ? Math.sin(x * Math.PI / 180) : operation === "cos" ? Math.cos(x * Math.PI / 180) : operation === "tan" ? Math.tan(x * Math.PI / 180) : operation === "sqrt" ? Math.sqrt(x) : operation === "log" ? Math.log10(x) : operation === "square" ? x * x : Math.pow(x, 3);
  return <Frame calc={calc} onReset={() => setValue("")} result={<Result label="Result" value={Number.isFinite(answer) ? answer.toFixed(6) : "Enter a valid value"} rows={[["Input", value || "—"], ["Operation", operation]]} formula="trigonometry uses degrees; logarithm is base 10" />}><div className="cn-field-grid two"><Field label="Value" value={value} onChange={setValue} /><SelectField label="Operation" value={operation} onChange={setOperation} options={[{ value: "sin", label: "sin (degrees)" }, { value: "cos", label: "cos (degrees)" }, { value: "tan", label: "tan (degrees)" }, { value: "sqrt", label: "Square root" }, { value: "log", label: "Log base 10" }, { value: "square", label: "Square" }, { value: "cube", label: "Cube" }]} /></div></Frame>;
}
function Loan() {
  const calc = calcFor("loan-calculator"); const [principal, setPrincipal] = useState("500000"); const [rate, setRate] = useState("9"); const [years, setYears] = useState("5"); const months = n(years) * 12; const monthlyRate = n(rate) / 1200; const payment = monthlyRate ? n(principal) * monthlyRate * Math.pow(1 + monthlyRate, months) / (Math.pow(1 + monthlyRate, months) - 1) : months ? n(principal) / months : 0; const total = payment * months;
  return <Frame calc={calc} onReset={() => { setPrincipal(""); setRate(""); setYears(""); }} result={<Result label="Monthly payment" value={`₹ ${payment.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`} rows={[["Total interest", `₹ ${Math.max(0, total - n(principal)).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`], ["Total repayment", `₹ ${total.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`], ["Payments", String(months)]]} formula="reducing-balance monthly payment formula" />}><div className="cn-field-grid"><Field label="Loan amount" value={principal} onChange={setPrincipal} /><Field label="Annual interest rate (%)" value={rate} onChange={setRate} /><Field label="Loan tenure (years)" value={years} onChange={setYears} /></div></Frame>;
}
function Savings() {
  const calc = calcFor("savings-calculator"); const [goal, setGoal] = useState("100000"); const [current, setCurrent] = useState("10000"); const [monthly, setMonthly] = useState("5000"); const [years, setYears] = useState("2"); const months = n(years) * 12; const planned = n(current) + n(monthly) * months; const remaining = Math.max(0, n(goal) - n(current)); const needed = months ? remaining / months : remaining;
  return <Frame calc={calc} onReset={() => { setGoal(""); setCurrent(""); setMonthly(""); setYears(""); }} result={<Result label="Goal check" value={planned >= n(goal) ? "On track" : `₹ ${needed.toFixed(0)} / month`} rows={[["Projected total", `₹ ${planned.toLocaleString("en-IN")}`], ["Still needed", `₹ ${Math.max(0, n(goal) - planned).toLocaleString("en-IN")}`], ["Time", `${months} months`]]} note="A simple planning estimate with no investment return assumed." />}><div className="cn-field-grid"><Field label="Savings goal" value={goal} onChange={setGoal} /><Field label="Already saved" value={current} onChange={setCurrent} /><Field label="Monthly saving" value={monthly} onChange={setMonthly} /><Field label="Time period (years)" value={years} onChange={setYears} /></div></Frame>;
}
function Tax() {
  const calc = calcFor("tax-calculator"); const [amount, setAmount] = useState("50000"); const [rate, setRate] = useState("18"); const [deductions, setDeductions] = useState("0"); const taxable = Math.max(0, n(amount) - n(deductions)); const tax = taxable * n(rate) / 100;
  return <Frame calc={calc} onReset={() => { setAmount(""); setRate(""); setDeductions("0"); }} result={<Result label="After-tax amount" value={`₹ ${(n(amount) - tax).toFixed(2)}`} rows={[["Taxable amount", `₹ ${taxable.toFixed(2)}`], ["Estimated tax", `₹ ${tax.toFixed(2)}`], ["Rate", `${rate}%`]]} note="This is a general estimate, not a tax filing or professional tax advice." />}><div className="cn-field-grid"><Field label="Income or price" value={amount} onChange={setAmount} /><Field label="Tax rate (%)" value={rate} onChange={setRate} /><Field label="Deductions" value={deductions} onChange={setDeductions} /></div></Frame>;
}
function Calorie() {
  const calc = calcFor("calorie-calculator"); const [age, setAge] = useState("25"); const [height, setHeight] = useState("170"); const [weight, setWeight] = useState("65"); const [sex, setSex] = useState("female"); const [activity, setActivity] = useState("1.55"); const bmr = sex === "male" ? 10 * n(weight) + 6.25 * n(height) - 5 * n(age) + 5 : 10 * n(weight) + 6.25 * n(height) - 5 * n(age) - 161; const calories = bmr * n(activity);
  return <Frame calc={calc} onReset={() => { setAge(""); setHeight(""); setWeight(""); }} result={<Result label="Daily calorie estimate" value={`${Math.round(calories).toLocaleString()} kcal`} rows={[["Resting needs", `${Math.round(bmr).toLocaleString()} kcal`], ["Activity level", activity === "1.2" ? "Sedentary" : activity === "1.55" ? "Moderate" : "Active"]]} note="General estimate only. Your needs can vary with health, goals, and routine." formula="Mifflin–St Jeor × activity level" />}><div className="cn-toggle-row"><button className={`cn-toggle ${sex === "female" ? "active" : ""}`} onClick={() => setSex("female")}>Female</button><button className={`cn-toggle ${sex === "male" ? "active" : ""}`} onClick={() => setSex("male")}>Male</button></div><div className="cn-field-grid two" style={{ marginTop: 18 }}><Field label="Age (years)" value={age} onChange={setAge} /><Field label="Height (cm)" value={height} onChange={setHeight} /><Field label="Weight (kg)" value={weight} onChange={setWeight} /><SelectField label="Activity level" value={activity} onChange={setActivity} options={[{ value: "1.2", label: "Sedentary" }, { value: "1.375", label: "Lightly active" }, { value: "1.55", label: "Moderately active" }, { value: "1.725", label: "Very active" }]} /></div></Frame>;
}
function IdealWeight() {
  const calc = calcFor("ideal-weight-calculator"); const [height, setHeight] = useState("170"); const lower = 18.5 * Math.pow(n(height) / 100, 2); const upper = 24.9 * Math.pow(n(height) / 100, 2);
  return <Frame calc={calc} onReset={() => setHeight("")} result={<Result label="General range" value={`${lower.toFixed(1)} – ${upper.toFixed(1)} kg`} rows={[["Height", `${height || 0} cm`], ["Lower BMI marker", "18.5"], ["Upper BMI marker", "24.9"]]} note="Weight ranges are broad screening references, not a personal health target." />}><Field label="Height (cm)" value={height} onChange={setHeight} /></Frame>;
}
function DaysBetween() {
  const calc = calcFor("days-between-calculator"); const [from, setFrom] = useState("2026-01-01"); const [to, setTo] = useState("2026-12-31"); const first = new Date(`${from}T00:00:00`); const second = new Date(`${to}T00:00:00`); const days = Number.isFinite(first.getTime()) && Number.isFinite(second.getTime()) ? Math.abs(Math.round((second.getTime() - first.getTime()) / 86400000)) : 0;
  return <Frame calc={calc} onReset={() => { setFrom(""); setTo(""); }} result={<Result label="Days between" value={`${days.toLocaleString()} days`} rows={[["Weeks", (days / 7).toFixed(1)], ["Months (approx.)", (days / 30.4375).toFixed(1)], ["Years (approx.)", (days / 365.25).toFixed(2)]]} note="The count uses your local calendar and includes leap-year dates." />}><div className="cn-field-grid two"><Field label="Start date" type="date" value={from} onChange={setFrom} /><Field label="End date" type="date" value={to} onChange={setTo} /></div></Frame>;
}
function TimeDuration() {
  const calc = calcFor("time-duration-calculator"); const [startHour, setStartHour] = useState("9"); const [startMinute, setStartMinute] = useState("30"); const [endHour, setEndHour] = useState("17"); const [endMinute, setEndMinute] = useState("45"); const start = n(startHour) * 60 + n(startMinute); const end = n(endHour) * 60 + n(endMinute); const duration = (end - start + 1440) % 1440;
  return <Frame calc={calc} onReset={() => { setStartHour(""); setStartMinute(""); setEndHour(""); setEndMinute(""); }} result={<Result label="Duration" value={`${Math.floor(duration / 60)}h ${duration % 60}m`} rows={[["Total minutes", String(duration)], ["Start", `${startHour || 0}:${String(startMinute || 0).padStart(2, "0")}`], ["End", `${endHour || 0}:${String(endMinute || 0).padStart(2, "0")}`]]} note="If the end time is earlier than the start, the calculator treats it as the next day." />}><div className="cn-time-block"><span className="cn-kicker">Start time</span><div className="cn-field-grid two"><Field label="Hours" value={startHour} onChange={setStartHour} /><Field label="Minutes" value={startMinute} onChange={setStartMinute} /></div></div><div className="cn-time-block"><span className="cn-kicker">End time</span><div className="cn-field-grid two"><Field label="Hours" value={endHour} onChange={setEndHour} /><Field label="Minutes" value={endMinute} onChange={setEndMinute} /></div></div></Frame>;
}
function FuelCost() {
  const calc = calcFor("fuel-cost-calculator"); const [distance, setDistance] = useState("250"); const [mileage, setMileage] = useState("15"); const [price, setPrice] = useState("105"); const litres = n(mileage) ? n(distance) / n(mileage) : 0; const cost = litres * n(price);
  return <Frame calc={calc} onReset={() => { setDistance(""); setMileage(""); setPrice(""); }} result={<Result label="Trip fuel cost" value={`₹ ${cost.toFixed(2)}`} rows={[["Fuel needed", `${litres.toFixed(2)} L`], ["Distance", `${distance || 0} km`], ["Fuel price", `₹ ${price || 0} / L`]]} formula="distance ÷ mileage × price per litre" />}><div className="cn-field-grid"><Field label="Trip distance (km)" value={distance} onChange={setDistance} /><Field label="Vehicle mileage (km/L)" value={mileage} onChange={setMileage} /><Field label="Fuel price (₹/L)" value={price} onChange={setPrice} /></div></Frame>;
}
function ElectricityCost() {
  const calc = calcFor("electricity-cost-calculator"); const [units, setUnits] = useState("100"); const [rate, setRate] = useState("8"); const [fixed, setFixed] = useState("100"); const cost = n(units) * n(rate) + n(fixed);
  return <Frame calc={calc} onReset={() => { setUnits(""); setRate(""); setFixed(""); }} result={<Result label="Estimated bill" value={`₹ ${cost.toFixed(2)}`} rows={[["Energy charge", `₹ ${(n(units) * n(rate)).toFixed(2)}`], ["Fixed charge", `₹ ${n(fixed).toFixed(2)}`], ["Usage", `${units || 0} kWh`]]} note="Actual bills can include slabs, taxes, and provider-specific charges." />}><div className="cn-field-grid"><Field label="Usage (kWh)" value={units} onChange={setUnits} /><Field label="Rate per kWh (₹)" value={rate} onChange={setRate} /><Field label="Fixed charge (₹)" value={fixed} onChange={setFixed} /></div></Frame>;
}
function SplitBill() {
  const calc = calcFor("split-bill-calculator"); const [bill, setBill] = useState("2400"); const [tip, setTip] = useState("10"); const [people, setPeople] = useState("4"); const tipAmount = n(bill) * n(tip) / 100; const total = n(bill) + tipAmount;
  return <Frame calc={calc} onReset={() => { setBill(""); setTip("10"); setPeople("4"); }} result={<Result label="Each person pays" value={`₹ ${(total / Math.max(1, n(people))).toFixed(2)}`} rows={[["Tip amount", `₹ ${tipAmount.toFixed(2)}`], ["Total bill", `₹ ${total.toFixed(2)}`], ["People", people || "1"]]} formula="(bill + tip) ÷ people" />}><div className="cn-field-grid"><Field label="Bill amount" value={bill} onChange={setBill} /><Field label="Tip (%)" value={tip} onChange={setTip} /><Field label="Number of people" value={people} onChange={setPeople} min="1" /></div></Frame>;
}
function PercentagePoints() {
  const calc = calcFor("percentage-points-calculator"); const [oldValue, setOldValue] = useState("18"); const [newValue, setNewValue] = useState("24"); const points = n(newValue) - n(oldValue); const relative = n(oldValue) ? points / n(oldValue) * 100 : 0;
  return <Frame calc={calc} onReset={() => { setOldValue(""); setNewValue(""); }} result={<Result label="Difference" value={`${points.toFixed(2)} percentage points`} rows={[["From", `${oldValue || 0}%`], ["To", `${newValue || 0}%`], ["Relative change", `${relative.toFixed(2)}%`]]} note="Percentage points compare the direct gap between two percentages." />}><div className="cn-field-grid two"><Field label="Original percentage" value={oldValue} onChange={setOldValue} /><Field label="New percentage" value={newValue} onChange={setNewValue} /></div></Frame>;
}

const CALC_COMPONENTS: Record<string, () => ReactNode> = { "basic-calculator": Basic, "percentage-calculator": Percentage, "emi-calculator": EMI, "sip-calculator": SIP, "gst-calculator": GST, "discount-calculator": Discount, "age-calculator": Age, "bmi-calculator": BMI, "bmr-calculator": BMR, "simple-interest-calculator": () => <Interest />, "compound-interest-calculator": () => <Interest compound />, "tip-calculator": Tip, "salary-calculator": Salary, "date-difference-calculator": DateDiff, "unit-converter": Converter, "currency-calculator": Currency, "fraction-calculator": Fraction, "average-calculator": Average, "ratio-calculator": Ratio, "scientific-calculator": Scientific, "loan-calculator": Loan, "savings-calculator": Savings, "tax-calculator": Tax, "calorie-calculator": Calorie, "ideal-weight-calculator": IdealWeight, "days-between-calculator": DaysBetween, "time-duration-calculator": TimeDuration, "fuel-cost-calculator": FuelCost, "electricity-cost-calculator": ElectricityCost, "split-bill-calculator": SplitBill, "percentage-points-calculator": PercentagePoints };
function CalculatorPage() { const { slug } = useParams<{ slug: string }>(); const Component = slug ? CALC_COMPONENTS[slug] : undefined; return Component ? <Component /> : <NotFound />; }

function InfoPage({ type }: { type: "about" | "privacy" | "terms" }) {
  const content = { about: { title: "A calmer place to calculate.", label: "About CalcNova", intro: "CalcNova was made for the moments when an answer should be simple, private, and close at hand.", sections: [["A useful kind of confidence", "Calculators should show their work without making you feel like you are back in a classroom. CalcNova pairs clear inputs with friendly results and the formula behind them."], ["Built for real life", "From comparing a salary offer to checking a tip, planning an investment, or counting down to a birthday, these are small decisions that deserve a good tool."], ["No account required", "Your calculations happen on your device. Favorites, recent tools, and your custom currency rates are kept in local browser storage."], ] }, privacy: { title: "Privacy, without the paperwork.", label: "Privacy policy", intro: "CalcNova is designed to work without accounts, servers, tracking, or external APIs.", sections: [["What stays on your device", "Theme preference, favorite calculators, recent calculator history, and editable currency rates are stored in your browser's localStorage. You can clear them from your browser settings at any time."], ["What we do not collect", "CalcNova does not ask for personal information and does not send your calculator inputs anywhere. Currency rates are manual and are never fetched live."], ["A note about health tools", "BMI and BMR are general educational estimates. They are not medical advice or a diagnosis. Consult a qualified professional for health decisions."]] }, terms: { title: "Simple terms for a simple tool.", label: "Terms of use", intro: "Use CalcNova freely for personal planning and everyday estimates.", sections: [["Use your judgment", "Results are estimates and should be checked against official statements, professional advice, or source documents when money, health, or legal decisions matter."], ["No warranties", "CalcNova is provided as-is. We work hard to keep formulas useful and the experience reliable, but cannot promise every result is suitable for every situation."], ["Respect the tool", "Do not attempt to disrupt, reverse engineer, or misuse the service. The calculator is free for ordinary personal and educational use."]] } }[type]; useMeta(content.title, content.intro); return <Shell><div className="cn-container"><article className="cn-prose"><SectionLabel>{content.label}</SectionLabel><h1 className="cn-display">{content.title}</h1><p style={{ fontSize: "1.05rem" }}>{content.intro}</p>{content.sections.map(([h, p]) => <section key={h}><h2>{h}</h2><p>{p}</p></section>)}</article></div></Shell>;
}
function Contact() { useMeta("Contact CalcNova", "Get in touch with the CalcNova team."); const [sent, setSent] = useState(false); return <Shell><div className="cn-container"><div className="cn-contact"><aside className="cn-contact-aside"><SectionLabel>Say hello</SectionLabel><h1 className="cn-display" style={{ fontSize: "clamp(2rem, 5vw, 3.7rem)", margin: "14px 0" }}>A better answer starts with a note.</h1><p>Found a rough edge, have a calculator idea, or want to tell us what you bookmark? We read every message.</p><div style={{ marginTop: 28, display: "flex", gap: 9, alignItems: "center", fontSize: ".82rem" }}><FileText size={17} /> hello@calcnova.example</div></aside><div className="cn-calculator-panel">{sent ? <div className="cn-empty"><ShieldCheck size={32} color="hsl(var(--accent))" /><h2 style={{ fontFamily: "var(--app-font-display)" }}>Message ready to go.</h2><p>Your email app can finish the conversation at hello@calcnova.example.</p><button className="cn-button cn-button-soft" onClick={() => setSent(false)} data-testid="button-send-another">Send another</button></div> : <form onSubmit={(e) => { e.preventDefault(); setSent(true); }}><div className="cn-panel-head"><div><div className="cn-kicker">Contact form</div><h2>What is on your mind?</h2></div></div><div className="cn-field-grid"><Field label="Your name" type="text" value="" onChange={() => undefined} placeholder="Your name" /><Field label="Email address" type="email" value="" onChange={() => undefined} placeholder="you@example.com" /></div><div className="cn-field" style={{ marginTop: 15 }}><label>Message</label><textarea className="cn-input" style={{ paddingTop: 12, minHeight: 130, resize: "vertical" }} placeholder="Tell us what would make CalcNova more useful." required data-testid="input-message" /></div><button className="cn-button cn-button-primary" style={{ marginTop: 18 }} type="submit" data-testid="button-submit-contact">Prepare message <ArrowRight size={16} /></button></form>}</div></div></div></Shell>; }

function Router() {
  const [location] = useLocation();
  return <ErrorBoundary resetKey={location}><Switch><Route path="/" component={Home} /><Route path="/calculator" component={Directory} /><Route path="/calculator/:slug" component={CalculatorPage} /><Route path="/about"><InfoPage type="about" /></Route><Route path="/privacy"><InfoPage type="privacy" /></Route><Route path="/terms"><InfoPage type="terms" /></Route><Route path="/contact" component={Contact} /><Route component={NotFound} /></Switch></ErrorBoundary>;
}
function App() { return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, "")}><Router /></WouterRouter><Toaster /></TooltipProvider></QueryClientProvider>; }
export default App;